# This is a basic workflow to help you get started with Actions

name: Run/Deploy website (muarachmann.com)

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-tests:
    strategy:
      matrix:
        go-version: [1.12]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - name: Install go dependency
      run: sudo apt-get install go-dep

    - name: Installing dependencies
      run: dep init

    - name: Test & Run go project
      run: go run main.go
