# This is a basic workflow to help you get started with Actions

name: Run/Deploy website (muarachmann.com)

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-tests:
    strategy:
      matrix:
        go-version: [1.12]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: /home/runner/work/muarachmann.com/muarachmann.com

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/muarachmann.com/muarachmann.com/go

    - name: Install go-dep
      run: sudo apt-get install go-dep

    - name: Installing dependencies
      run: dep init

    - name: Test & Run go project
      run: go run main.go
